#!/usr/bin/env bash
#setting up load balancing
sudo apt update -y
sudo apt install haproxy -y
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy
printf %s 'listen 5515-webs
        server 5641-web-01 54.208.99.32 check
        server 5641-web-02 54.242.6.128 check
        bind *:80
        mode http
        balance roundrobin
' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
