#!/bin/bash

#!/usr/bin/env bash
# Install and configure haproxy.

sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*

cat >> /etc/haproxy/haproxy.cfg << EOF
frontend Local_Server
        bind *:80
        mode http
        default_backend Web_Servers
backend Web_Servers
        balance roundrobin
        mode http
        server web-01 54.208.99.32:80 check
        server web-02 54.242.6.128:80 check
EOF

sudo service haproxy restart

